### ISSUE TITLE
Les fichiers avec des espaces sont mal pris en compte

### ISSUE THREAD

**Issue by jd-develop** [Alexiscomete/FebruaryChallenge2021#3]
![image](https://user-images.githubusercontent.com/65287945/144999227-5bfb2e5b-a2a2-4f92-8cea-a13f7df48ce7.png)

![image](https://user-images.githubusercontent.com/65287945/144999324-63a0b606-cdb9-4aac-aaa4-0835fb389567.png)

![image](https://user-images.githubusercontent.com/65287945/144999378-18df768d-0224-48b9-8b75-e03565c75029.png)

Jusque là tout va bien (entre-temps j'ai ajouté du contenu au fichier avec espaces)

![image](https://user-images.githubusercontent.com/65287945/145014282-65a62b8b-f165-4cbc-a08c-f6e3ffd895ff.png)
Et voilà... Ca ne marche pas non plus avec mon environnement Windows. J'utilise Java 17.

**Comment by Alexiscomete** [comment]
🤔

**Comment by jd-develop** [comment]
Je suis en train de corriger ce bug, @Alexiscomete quel est le mieux entre ces propositions ? :
* `fichier avec espaces`
* `fichier\ avec\ espaces` (plus logique car utilisé dans Linux)
* `"fichier avec espaces"` (utilisé dans Windows, le seul problème est rencontré avec les fichiers ext4 (linux) qui contiennent le caractère " dans le nom)
* `'fichier avec espaces'` (même pb)

**Comment by Alexiscomete** [comment]
Au départ je pensais utiliser le premier, celui utilisé par Linux me semble bien 
Après ce n'est pas moi qui interprète le chemin mais directement Java

**Comment by Alexiscomete** [comment]
Peut-être que le problème viens simplement du fait que je prend l'argument d'index 1 au lieu de prendre toute la fin de la ligne

**Comment by jd-develop** [comment]
> Peut-être que le problème viens simplement du fait que je prend l'argument d'index 1 au lieu de prendre toute la fin de la ligne

Oui ça doit être ça en effet ^^

**Comment by Alexiscomete** [comment]
😅

**Comment by jd-develop** [comment]
Je crois que j'ai trouvé un bon patch, je vais le tester ^^

**Comment by Alexiscomete** [comment]
J'ai regardé ton commit, je pense que l'on pourrait plutôt utiliser content.substring(index du début du chemin);

**Comment by Alexiscomete** [comment]
Sinon c'est cool
