### ISSUE TITLE
Le ~ est mal pris en compte

### ISSUE THREAD

**Issue by jd-develop** [Alexiscomete/FebruaryChallenge2021#4]
Sur cette image, on observe que le ~ n'est pas pris en compte comme un dossier. Il correspond au /home/nomdutilisateur/ dans Linux et à %userprofile% dans Windows. :)

![image](https://user-images.githubusercontent.com/65287945/145014732-1ec443b2-22e4-471f-96b4-29d61f3eb414.png)

**Comment by Alexiscomete** [comment]
Je vois ... effectivement je n'ai pas beaucoup utilisé Linux donc je n'y ai pas pensé au moment de créer le programme. Je vais essayer de corriger ça. Merci pour le signalement

**Comment by Alexiscomete** [comment]
Quand je regarde ce projet auquel je n'ai pas touché depuis des mois, maintenant je vois plein de choses à changer 😭

**Comment by jd-develop** [comment]
Haha, ça m'arrive avec des projets à moi... Bon courage :)

**Comment by Alexiscomete** [comment]
merci

**Comment by Alexiscomete** [comment]
je pense qu'en plus c'est mon projet le plus abouti
